# Generated by Django 4.2.3 on 2023-07-12 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("User", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scripts",
            name="Plot",
            field=models.CharField(default="NULL", max_length=500),
        ),
    ]
