# Generated by Django 4.2.3 on 2023-07-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("User", "0002_scripts_plot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="scripts",
            field=models.ManyToManyField(default="NULL", to="User.scripts"),
        ),
    ]
